# Generated by Django 5.1.7 on 2025-03-26 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "global_markup_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProposalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("position", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=255)),
                (
                    "client_signature",
                    models.FileField(blank=True, null=True, upload_to="signatures/"),
                ),
                ("client_initials", models.CharField(blank=True, max_length=10)),
                ("contractor_name", models.CharField(max_length=255)),
                (
                    "contractor_signature",
                    models.FileField(blank=True, null=True, upload_to="signatures/"),
                ),
                ("contractor_initials", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("client_signed_at", models.DateTimeField(blank=True, null=True)),
                ("contractor_signed_at", models.DateTimeField(blank=True, null=True)),
                ("terms_and_conditions", models.TextField()),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to="api.proposal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProposalElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "material_cost",
                    models.CharField(
                        help_text="Formula or fixed value", max_length=255
                    ),
                ),
                (
                    "labor_cost",
                    models.CharField(
                        help_text="Formula or fixed value", max_length=255
                    ),
                ),
                (
                    "markup_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("position", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements",
                        to="api.proposalcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="ProposalVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LINEAR_FEET", "Linear Feet"),
                            ("SQUARE_FEET", "Square Feet"),
                            ("CUBIC_FEET", "Cubic Feet"),
                            ("COUNT", "Count"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="api.template",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="proposalcategory",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="api.template",
            ),
        ),
        migrations.AddField(
            model_name="proposal",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proposals",
                to="api.template",
            ),
        ),
        migrations.CreateModel(
            name="ProposalElementValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calculated_material_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "calculated_labor_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "markup_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "element",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="api.proposalelement",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="element_values",
                        to="api.proposal",
                    ),
                ),
            ],
            options={
                "unique_together": {("proposal", "element")},
            },
        ),
        migrations.CreateModel(
            name="ProposalVariableValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variable_values",
                        to="api.proposal",
                    ),
                ),
                (
                    "variable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="api.proposalvariable",
                    ),
                ),
            ],
            options={
                "unique_together": {("proposal", "variable")},
            },
        ),
    ]
