# Generated by Django 5.1.7 on 2025-03-27 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposalcategory",
            name="proposal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="direct_categories",
                to="api.proposal",
            ),
        ),
        migrations.AddField(
            model_name="proposalelement",
            name="proposal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="direct_elements",
                to="api.proposal",
            ),
        ),
        migrations.AddField(
            model_name="proposalvariable",
            name="proposal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="direct_variables",
                to="api.proposal",
            ),
        ),
        migrations.AlterField(
            model_name="proposalcategory",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="api.template",
            ),
        ),
        migrations.AlterField(
            model_name="proposalelement",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="api.proposalcategory",
            ),
        ),
        migrations.AlterField(
            model_name="proposalvariable",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variables",
                to="api.template",
            ),
        ),
    ]
