# Generated by Django 5.1.7 on 2025-03-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_proposalcategory_proposal_proposalelement_proposal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposalvariable",
            name="default_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
