# Generated by Django 5.1.7 on 2025-03-28 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_proposalvariable_default_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="contract",
            name="proposal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="api.proposal",
            ),
        ),
    ]
